[2024-11-26T19:46:13.373+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-26T19:46:13.381+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Weather_Realtime_Data_ETL.load_weather_current_data manual__2024-11-26T19:46:10.476014+00:00 [queued]>
[2024-11-26T19:46:13.386+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Weather_Realtime_Data_ETL.load_weather_current_data manual__2024-11-26T19:46:10.476014+00:00 [queued]>
[2024-11-26T19:46:13.386+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-26T19:46:13.391+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_weather_current_data> on 2024-11-26 19:46:10.476014+00:00
[2024-11-26T19:46:13.395+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=21529) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-26T19:46:13.396+0000] {standard_task_runner.py:63} INFO - Started process 21532 to run task
[2024-11-26T19:46:13.395+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Weather_Realtime_Data_ETL', 'load_weather_current_data', 'manual__2024-11-26T19:46:10.476014+00:00', '--job-id', '251', '--raw', '--subdir', 'DAGS_FOLDER/ETL_weather_realtime.py', '--cfg-path', '/tmp/tmpagu79kvf']
[2024-11-26T19:46:13.397+0000] {standard_task_runner.py:91} INFO - Job 251: Subtask load_weather_current_data
[2024-11-26T19:46:13.419+0000] {task_command.py:426} INFO - Running <TaskInstance: Weather_Realtime_Data_ETL.load_weather_current_data manual__2024-11-26T19:46:10.476014+00:00 [running]> on host 5de3b6ca18a7
[2024-11-26T19:46:13.487+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='shatayu.thakur@sjsu.edu' AIRFLOW_CTX_DAG_OWNER='Shatayu' AIRFLOW_CTX_DAG_ID='Weather_Realtime_Data_ETL' AIRFLOW_CTX_TASK_ID='load_weather_current_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-26T19:46:10.476014+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-26T19:46:10.476014+00:00'
[2024-11-26T19:46:13.488+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-26T19:46:13.493+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-11-26T19:46:13.493+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.0, Python Version: 3.12.3, Platform: Linux-6.10.11-linuxkit-aarch64-with-glibc2.36
[2024-11-26T19:46:13.494+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-11-26T19:46:13.985+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-26T19:46:13.992+0000] {logging_mixin.py:188} INFO - Realtime Record to be pushed to snowflake table:                   date  temp  temp_feel  humidity  rain  year  month  day  hour
0 2024-11-26 14:30:00  60.1       60.1        60  2.01  2024     11   26    14
[2024-11-26T19:46:14.086+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-26T19:46:14.185+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-26T19:46:14.613+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-26T19:46:14.613+0000] {logging_mixin.py:188} INFO - Target Table Initialized and Ready to Store Realtime Weather Data from ETL
[2024-11-26T19:46:15.096+0000] {logging_mixin.py:188} INFO - Inserted current weather for date: 2024-11-26 14:30:00
[2024-11-26T19:46:15.097+0000] {logging_mixin.py:188} INFO - Inserted current weather record successfully to dev.raw_data.weather_current through query: 
            MERGE INTO dev.raw_data.weather_current AS target
            USING (SELECT '2024-11-26 14:30:00' AS date, 60.1 AS temp, 60.1 AS temp_feel, 
                        60 AS humidity, 2.01 AS rain, 2024 AS year, 
                        11 AS month, 26 AS day, 14 AS hour) AS source
            ON target.date = source.date
            WHEN MATCHED THEN 
                UPDATE SET target.temp = source.temp, target.temp_feel = source.temp_feel, 
                        target.humidity = source.humidity, target.rain = source.rain, 
                        target.year = source.year, target.month = source.month, 
                        target.day = source.day, target.hour = source.hour
            WHEN NOT MATCHED THEN
                INSERT (date, temp, temp_feel, humidity, rain, year, month, day, hour) 
                VALUES (source.date, source.temp, source.temp_feel, source.humidity, 
                        source.rain, source.year, source.month, source.day, source.hour);
            
[2024-11-26T19:46:15.184+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-26T19:46:15.186+0000] {logging_mixin.py:188} INFO - Transaction committed. Data load complete.
[2024-11-26T19:46:15.187+0000] {connection.py:762} INFO - closed
[2024-11-26T19:46:15.227+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-11-26T19:46:15.281+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-26T19:46:15.282+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-26T19:46:15.300+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Weather_Realtime_Data_ETL, task_id=load_weather_current_data, run_id=manual__2024-11-26T19:46:10.476014+00:00, execution_date=20241126T194610, start_date=20241126T194613, end_date=20241126T194615
[2024-11-26T19:46:15.352+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-26T19:46:15.366+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-26T19:46:15.367+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
