[2024-11-25T07:14:45.914+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-25T07:14:45.925+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Citibike_Data_ETL.load_citibike_data manual__2024-11-25T07:12:58.867163+00:00 [queued]>
[2024-11-25T07:14:45.928+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Citibike_Data_ETL.load_citibike_data manual__2024-11-25T07:12:58.867163+00:00 [queued]>
[2024-11-25T07:14:45.929+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-25T07:14:45.934+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_citibike_data> on 2024-11-25 07:12:58.867163+00:00
[2024-11-25T07:14:45.940+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=8530) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T07:14:45.941+0000] {standard_task_runner.py:63} INFO - Started process 8533 to run task
[2024-11-25T07:14:45.940+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Citibike_Data_ETL', 'load_citibike_data', 'manual__2024-11-25T07:12:58.867163+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/ETL_citibike.py', '--cfg-path', '/tmp/tmpluyk8u84']
[2024-11-25T07:14:45.942+0000] {standard_task_runner.py:91} INFO - Job 87: Subtask load_citibike_data
[2024-11-25T07:14:45.973+0000] {task_command.py:426} INFO - Running <TaskInstance: Citibike_Data_ETL.load_citibike_data manual__2024-11-25T07:12:58.867163+00:00 [running]> on host 5de3b6ca18a7
[2024-11-25T07:14:46.027+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='shatayu.thakur@sjsu.edu' AIRFLOW_CTX_DAG_OWNER='Shatayu' AIRFLOW_CTX_DAG_ID='Citibike_Data_ETL' AIRFLOW_CTX_TASK_ID='load_citibike_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T07:12:58.867163+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-25T07:12:58.867163+00:00'
[2024-11-25T07:14:46.028+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-25T07:14:46.035+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-11-25T07:14:46.036+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.0, Python Version: 3.12.3, Platform: Linux-6.10.11-linuxkit-aarch64-with-glibc2.36
[2024-11-25T07:14:46.036+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-11-25T07:14:46.609+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-25T07:14:52.398+0000] {logging_mixin.py:188} INFO - Row count for data to be pushed:  2982715
[2024-11-25T07:14:52.877+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-25T07:14:52.878+0000] {logging_mixin.py:188} INFO - Stage created successfully.
[2024-11-25T07:15:14.153+0000] {logging_mixin.py:188} INFO - File uploaded to stage: /opt/***/temp_store_proj/cleaned_data.csv
[2024-11-25T07:15:14.603+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-25T07:15:14.603+0000] {logging_mixin.py:188} INFO - Target Table Initialized and Ready to Store Data from ETL
[2024-11-25T07:15:14.853+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-25T07:15:14.854+0000] {logging_mixin.py:188} INFO - An error occurred during stock data load: 090106 (22000): 01b89a33-0004-3864-0002-55f3000417a6: Cannot perform operation. This session does not have a current schema. Call 'USE SCHEMA', or use a qualified name.
[2024-11-25T07:15:14.855+0000] {connection.py:762} INFO - closed
[2024-11-25T07:15:14.902+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-11-25T07:15:15.176+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-25T07:15:15.178+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-25T07:15:15.193+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Citibike_Data_ETL, task_id=load_citibike_data, run_id=manual__2024-11-25T07:12:58.867163+00:00, execution_date=20241125T071258, start_date=20241125T071445, end_date=20241125T071515
[2024-11-25T07:15:15.276+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-25T07:15:15.289+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-25T07:15:15.290+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
